package com.safeedge.bankroll;

public enum BankrollTransactionType {
	BET_SETTLED_WIN,
	BET_SETTLED_HALF_WIN,
	BET_SETTLED_PUSH,
	BET_SETTLED_HALF_LOSS,
	BET_SETTLED_LOSS,
	VAULT_SWEEP,
	VAULT_TRANSFER_TO_ACTIVE,
	DEPOSIT,
	ACTIVE_WITHDRAWAL,
	VAULT_WITHDRAWAL
}
