package com.safeedge.strategy;

public enum StrategyDecisionReason {
	EDGE_BELOW_MINIMUM,
	NON_POSITIVE_EXPECTED_RETURN,
	DRAWDOWN_WARNING,
	DRAWDOWN_REDUCTION_APPLIED,
	DRAWDOWN_STOP,
	MAX_STAKE_CAPPED,
	MATCH_EXPOSURE_CAPPED,
	LEAGUE_EXPOSURE_CAPPED,
	DAILY_EXPOSURE_CAPPED,
	NO_EXPOSURE_CAPACITY,
	NO_ACTIVE_BANKROLL
}
